SEED: 42
DATA:
  data_dir: ./data/raw/retinamnist
  name: "retinamnist"
  img_size: 32
  num_classes: 5
  img_channels: 3

PRE:
  crop_long_edge: True
  resize_size: 32
  pre_resizer: "lanczos"
  normalize: True
  apply_rflip: False

MODEL:
  name: resnet_ae_101
  h_dim:
  dropout_rate: 0.25

TRAINER:
  batch_size: 64
  optimizer:
    lr: 0.001 # initial learning rate
    weight_decay: 0.00001 # weight decay
  scheduler: # allow to change learning rate during training
    mode: min
    patience: 5 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
  early_stopping: 25 # if the validation loss do not improve for x epochs stop training
  warmup_epoch: 25 # number of epochs to warmup
  max_epochs: 100