DATA:
  name: "retinamnist"
  img_size: 32
  num_classes: 5
  img_channels: 3
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [2]
  attn_d_loc: [1]
LOSS:
  adv_loss: "hinge"
