SEED: 42
DATA:
  data_dir: ./data/raw/retinamnist
  name: "retinamnist"
  img_size: 32
  num_classes: 5
  img_channels: 3
  hdf5:
  load_data_in_memory: False
PRE:
  crop_long_edge: True
  resize_size: 32
  pre_resizer: "lanczos"
  normalize: True
  apply_rflip: False